[package]
name = "dropspace"
version = "1.0.0"
authors = []

[addresses]
dropspace="4ba102cb3dbad5204e2bb4d6625cb05bf01ce55f512762ace9169bf04155d32b"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token"

[dev-dependencies]
